export const departureData = {
  departures: {
    VHHH: {
      "07R": [
        "BEKOL1X",
        "BEKOL5A",
        "LEKEN1X",
        "LEKEN1A",
        "DALOL1X",
        "DALOL1A",
        "PECAN3X",
        "PECAN3A",
        "RAMEN2A"
      ],
      "07C": [
        "ADLAD1T",
        "BEKOL1Y",
        "BEKOL1C",
        "LARIT1T",
        "LEKEN1Y",
        "LEKEN1C",
        "DUMEP1T",
        "DALOL1Y",
        "DALOL1C",
        "XEMEK1T",
        "SOSLU1T",
        "PECAN1Y",
        "PECAN1C",
        "RAMEN1C"
      ],
      "07L": [
        "BEKOL1Z",
        "BEKOL2E",
        "LEKEN1Z",
        "LEKEN1E",
        "DALOL1Z",
        "DALOL1E",
        "PECAN2Z",
        "PECAN2E",
        "RAMEN1E"
      ],
      "25L": [
        "BEKOL3B",
        "LEKEN1B",
        "DALOL1B",
        "PECAN2B",
        "RUMSY2B"
      ],
      "25C": [
        "BEKOL1D",
        "LEKEN1D",
        "DALOL1D",
        "PECAN1D",
        "RUMSY1D"
      ],
      "25R": [
        "BEKOL2F",
        "LEKEN1F",
        "DALOL1F",
        "PECAN2F",
        "RUMSY1F"
      ]
    },
    VMMC: {
      "16": [
        "NLG1H",
        "NLG2D",
        "SHL1H",
        "SHL2D",
        "MIPAG1H",
        "MIPAG2D",
        "BIGRO1H",
        "BIGRO2D",
        "NUDPI1P",
        "CONGA2P",
        "GRUPA2P",
        "ALLEY2P"
      ],
      "34": [
        "NLG1G",
        "NLG7D",
        "SHL1G",
        "SHL2G",
        "MIPAG1G",
        "MIPAG7D",
        "BIGRO1G",
        "BIGRO7D",
        "NUDPI1T",
        "NUDPI1U",
        "CONGA4T",
        "CONGA5U",
        "GRUPA4T",
        "GRUPA5U",
        "ALLEY4T",
        "ALLEY4U"
      ]
    },
    VHHX: {
      "13": [
        "BEKOL1A",
        "DOTMI1A",
        "ELATO1A",
        "ENVAR1A",
        "NOMAN1A",
        "NOMAN1B",
        "SABNO1A",
        "SABNO1B",
        "SIKOU1A",
        "IDOSI1A",
        "IDOSI1B",
        "EPDOS1A"
      ],
      "31": [
        "BEKOL2C",
        "DOTMI2C",
        "ELATO2C",
        "ENVAR2C",
        "NOMAN2C",
        "NOMAN2D",
        "SABNO2C",
        "SABNO2D",
        "SIKOU2C",
        "SIKOU2E",
        "IDOSI2C",
        "IDOSI2D",
        "EPDOS2C"
      ]
    }
  },
  sidMapping: {
    "BEKOL1X": { airport: "VHHH", runway: "07R" },
    "BEKOL5A": { airport: "VHHH", runway: "07R" },
    "LEKEN1X": { airport: "VHHH", runway: "07R" },
    "LEKEN1A": { airport: "VHHH", runway: "07R" },
    "DALOL1X": { airport: "VHHH", runway: "07R" },
    "DALOL1A": { airport: "VHHH", runway: "07R" },
    "PECAN3X": { airport: "VHHH", runway: "07R" },
    "PECAN3A": { airport: "VHHH", runway: "07R" },
    "RAMEN2A": { airport: "VHHH", runway: "07R" },
    "ADLAD1T": { airport: "VHHH", runway: "07C" },
    "BEKOL1Y": { airport: "VHHH", runway: "07C" },
    "BEKOL1C": { airport: "VHHH", runway: "07C" },
    "LARIT1T": { airport: "VHHH", runway: "07C" },
    "LEKEN1Y": { airport: "VHHH", runway: "07C" },
    "LEKEN1C": { airport: "VHHH", runway: "07C" },
    "DUMEP1T": { airport: "VHHH", runway: "07C" },
    "DALOL1Y": { airport: "VHHH", runway: "07C" },
    "DALOL1C": { airport: "VHHH", runway: "07C" },
    "XEMEK1T": { airport: "VHHH", runway: "07C" },
    "SOSLU1T": { airport: "VHHH", runway: "07C" },
    "PECAN1Y": { airport: "VHHH", runway: "07C" },
    "PECAN1C": { airport: "VHHH", runway: "07C" },
    "RAMEN1C": { airport: "VHHH", runway: "07C" },
    "BEKOL1Z": { airport: "VHHH", runway: "07L" },
    "BEKOL2E": { airport: "VHHH", runway: "07L" },
    "LEKEN1Z": { airport: "VHHH", runway: "07L" },
    "LEKEN1E": { airport: "VHHH", runway: "07L" },
    "DALOL1Z": { airport: "VHHH", runway: "07L" },
    "DALOL1E": { airport: "VHHH", runway: "07L" },
    "PECAN2Z": { airport: "VHHH", runway: "07L" },
    "PECAN2E": { airport: "VHHH", runway: "07L" },
    "RAMEN1E": { airport: "VHHH", runway: "07L" },
    "BEKOL3B": { airport: "VHHH", runway: "25L" },
    "LEKEN1B": { airport: "VHHH", runway: "25L" },
    "DALOL1B": { airport: "VHHH", runway: "25L" },
    "PECAN2B": { airport: "VHHH", runway: "25L" },
    "RUMSY2B": { airport: "VHHH", runway: "25L" },
    "BEKOL1D": { airport: "VHHH", runway: "25C" },
    "LEKEN1D": { airport: "VHHH", runway: "25C" },
    "DALOL1D": { airport: "VHHH", runway: "25C" },
    "PECAN1D": { airport: "VHHH", runway: "25C" },
    "RUMSY1D": { airport: "VHHH", runway: "25C" },
    "BEKOL2F": { airport: "VHHH", runway: "25R" },
    "LEKEN1F": { airport: "VHHH", runway: "25R" },
    "DALOL1F": { airport: "VHHH", runway: "25R" },
    "PECAN2F": { airport: "VHHH", runway: "25R" },
    "RUMSY1F": { airport: "VHHH", runway: "25R" },
    "NLG1H": { airport: "VMMC", runway: "16" },
    "NLG2D": { airport: "VMMC", runway: "16" },
    "SHL1H": { airport: "VMMC", runway: "16" },
    "SHL2D": { airport: "VMMC", runway: "16" },
    "MIPAG1H": { airport: "VMMC", runway: "16" },
    "MIPAG2D": { airport: "VMMC", runway: "16" },
    "BIGRO1H": { airport: "VMMC", runway: "16" },
    "BIGRO2D": { airport: "VMMC", runway: "16" },
    "NUDPI1P": { airport: "VMMC", runway: "16" },
    "CONGA2P": { airport: "VMMC", runway: "16" },
    "GRUPA2P": { airport: "VMMC", runway: "16" },
    "ALLEY2P": { airport: "VMMC", runway: "16" },
    "NLG1G": { airport: "VMMC", runway: "34" },
    "NLG7D": { airport: "VMMC", runway: "34" },
    "SHL1G": { airport: "VMMC", runway: "34" },
    "SHL2G": { airport: "VMMC", runway: "34" },
    "MIPAG1G": { airport: "VMMC", runway: "34" },
    "MIPAG7D": { airport: "VMMC", runway: "34" },
    "BIGRO1G": { airport: "VMMC", runway: "34" },
    "BIGRO7D": { airport: "VMMC", runway: "34" },
    "NUDPI1T": { airport: "VMMC", runway: "34" },
    "NUDPI1U": { airport: "VMMC", runway: "34" },
    "CONGA4T": { airport: "VMMC", runway: "34" },
    "CONGA5U": { airport: "VMMC", runway: "34" },
    "GRUPA4T": { airport: "VMMC", runway: "34" },
    "GRUPA5U": { airport: "VMMC", runway: "34" },
    "ALLEY4T": { airport: "VMMC", runway: "34" },
    "ALLEY4U": { airport: "VMMC", runway: "34" },
    "BEKOL1A": { airport: "VHHX", runway: "13" },
    "DOTMI1A": { airport: "VHHX", runway: "13" },
    "ELATO1A": { airport: "VHHX", runway: "13" },
    "ENVAR1A": { airport: "VHHX", runway: "13" },
    "NOMAN1A": { airport: "VHHX", runway: "13" },
    "NOMAN1B": { airport: "VHHX", runway: "13" },
    "SABNO1A": { airport: "VHHX", runway: "13" },
    "SABNO1B": { airport: "VHHX", runway: "13" },
    "SIKOU1A": { airport: "VHHX", runway: "13" },
    "IDOSI1A": { airport: "VHHX", runway: "13" },
    "IDOSI1B": { airport: "VHHX", runway: "13" },
    "EPDOS1A": { airport: "VHHX", runway: "13" },
    "BEKOL2C": { airport: "VHHX", runway: "31" },
    "DOTMI2C": { airport: "VHHX", runway: "31" },
    "ELATO2C": { airport: "VHHX", runway: "31" },
    "ENVAR2C": { airport: "VHHX", runway: "31" },
    "NOMAN2C": { airport: "VHHX", runway: "31" },
    "NOMAN2D": { airport: "VHHX", runway: "31" },
    "SABNO2C": { airport: "VHHX", runway: "31" },
    "SABNO2D": { airport: "VHHX", runway: "31" },
    "SIKOU2C": { airport: "VHHX", runway: "31" },
    "SIKOU2E": { airport: "VHHX", runway: "31" },
    "IDOSI2C": { airport: "VHHX", runway: "31" },
    "IDOSI2D": { airport: "VHHX", runway: "31" },
    "EPDOS2C": { airport: "VHHX", runway: "31" }
  }
};
